### ISSUE TITLE
Help figuring out why principal axes are assymetrical for a symmetrical 3D model

### ISSUE THREAD

**Issue by amadorkane** [AntonSemechko/Rigid-Body-Parameters#3]
Quick question:  we have a highly symmetrical mesh (a 3D Blender model of an insect).  We also have your code working to compute the inertia tensor and show the principal axes for various test cases. However, for this Blender model the principal axes are very assymetrically oriented.  We're running the ConsistentNormalOrientation.m code you provide to make sure there's consistent normal face orientation.  That helped us catch a duplicated face, which we fixed.  Do you have any other ideas what else might be going wrong, or what else we might check to debug?
Thanks!
Suzanne

**Comment by AntonSemechko** [comment]
Note this is a usage question, not a bug. Just in case this issue comes up with other users, I am posting relevant excerpts of my response to Suzanne here. 

1) If coordinates of the mesh vertices are expressed in units like meters and the object is very 'small' relative to the units chosen, you may see non-negligible round-off errors during the calculation of the inertia tensor on account of the squaring and cubing operations used to compute 2nd order moments.

2) If your goal is to compare multiple samples of the same type of object, using 2nd order geometric info is often insufficient for establishing consistent body-frames, especially if the objects have either "spherical" or "cylindrical" inertia tensors (i.e., 3 equal or 2 equal eigenvalues).

3) The rigid body parameter (RBP) function already checks that the mesh is closed and manifold (i.e., each edge is shared by two faces), and the preprocessing function verifies that the mesh is one connected structure and has properly oriented faces. Together these checks ensure that mesh is valid for RBP calculation. The disagreement between your expectation of where the principal axes should be and the actual result may be a limitation of using the RBP method to define body-centric reference frames.
